### ISSUE TITLE
Errors on site without expected parameters set

### ISSUE THREAD

**Issue by paskal** [christianmendoza/hugo-split-theme#4]
Hello!

$subj, when trying to run this theme against my [blog](https://github.com/paskal/terrty/tree/master/blog) source I get following (and site won't render at all):

```
Building sites … ERROR 2018/03/20 17:34:59 Error while rendering "home" in "": template: theme/index.html:34:11: executing "theme/index.html" at <partial "bio" .>: error calling partial: template: theme/partials/bio.html:2:35: executing "theme/partials/bio.html" at <markdownify>: wrong number of args for markdownify: want 1 got 0
```

The reason is likely some absent `.Site.` parameter but you can't tell it from error message, I guess input parameters handling could be improved. https://github.com/cboettig/hugo-now-ui/issues/9 might be used as reference point.

**Comment by paskal** [comment]
https://github.com/hivickylai/hugo-theme-sam/pull/3 is an example of how this can be fixed.

**Comment by escalate** [comment]
Hello @paskal,

thank you for you issue. I received the ownership for this project and will try to fix your problem.
But when I use the exampleSite from hugo-split-theme I can't reproduce your issue.
Could you please give me more information to reproduce this issue?

**Comment by paskal** [comment]
Empty config.json except theme option, expected result - everything is working, now site doesn't render. If you wish, I could give you a PR — I'm happy to give one to someone who will accept it.

**Comment by escalate** [comment]
Thank you for the additional information. It would be very helpful if you could provide a PR for the changes. Please use my repository at https://github.com/escalate/hugo-split-theme for the PR. Thank you very much for your help.

**Comment by escalate** [comment]
Your fix works. Thank you for your contribution. 

This issue is solved with PR https://github.com/escalate/hugo-split-theme/pull/2
